[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.10
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
    adafruit/Adafruit BusIO@^1.16.1
    
    bblanchon/ArduinoJson@^6.21.0
build_flags =
    -D USER_SETUP_LOADED=1